logging:
  level:
    org.hibernate.type.descriptor.sql: ERROR

spring:
  datasource:
    url: jdbc://mysql/db:3306
    username: user
    password: password

  jpa:
    show-sql: false

  liquibase:
    contexts: prod
